#encoding:utf-8
from etc import *
from common_inc import *

def du_oauth_device(appkey,appsec):
    device_para = 'client_id={}&response_type=device_code&scope=basic,netdisk'
    device_json = do_api('https://openapi.baidu.com/oauth/2.0/device/code',device_para)
    device_array = device_json.split('\n')[:-1]
    oaerr(device_array)
    print("Launch your favorite web browser and visit {}[verification_url]"
          "Input {}[user_code] as the user code if asked."
          "After granting access to the application, come back here and press Enter to continue.".format(device_array,device_array))
    while True:
        token_pare = 'grant_type=device_token&code={}&client_id={}&client_secret={}'\
            .format(device_array['device_code'],appkey,appsec)
        token_json = do_api('https://openapi.baidu.com/oauth/2.0/token',token_pare)
        token_array = token_json.split('\n')[:-1]
        if oaerr(token_array,0):
            break
        else:
            echon("Authentication failed. Please check the error message and try again.")
            print"Launch your favorite web browser and visit{} " \
                 "Input {} as the user code if asked." \
                 "After granting access to the application, come back here and press Enter to continue."\
                .format(device_array['verification_url'],device_array['user_code'])
            continueornot()
            continue
    access_token = token_array['access_token']
    refresh_token = token_array['refresh_token']
    return {'access_token':access_token,'refesh_token':refresh_token}
def do_oauth_token(appkey):
    print("In the next step, you'll have to grab the access_token generated by Baidu."
          "You can check out this link for more information on this procedure."
          "http://developer.baidu.com/wiki/index.php?title=docs/pcs/guide/usage_example"
          "Easy Guide:"
          "1. Visit https://openapi.baidu.com/oauth/2.0/authorize?response_type=token&client_id={}&redirect_uri=oob&scope=netdisk"
          "2. After the page is being redirected (it should show something like OAuth 2.0), copy the current URL to your favorite text editor."
          "3. Grab the access_token part, take only the part between 'access_token=' and the next '&' symbol (without quotes)."
          "4. Copy it and paste here, then press Enter.").format(appkey)
    print("access_token[]:")
    access_token = raw_input()
    return access_token

def do_oauth_refresh(appkey,appsec,refresh_token):
    para =  "grant_type=refresh_token&refresh_token={}&client_id={}&client_secret={}"\
        .format(refresh_token,appkey,appsec)
    token_json = do_api('https://openapi.baidu.com/oauth/2.0/token',para)
    token_array = token_json.split('\n')[:-1]
    access_token = token_array['access_token']
    refresh_token = token_array['refresh_token']
    return {'access_token':access_token,'refesh_token':refresh_token}

def get_quota(access_token):
    quota = do_api('https://pcs.baidu.com/rest/2.0/pcs/quota',"method=info&access_token={}"
                   .format(access_token),'GET')
    quota=quota.split('\n')[:-1]
    apierr(quota)
    return quota

def upload_file(access_token,path,localfile,ondup='newcopy'):
    path=getpath(path)
    url = 'https://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&access_token={}&path={}&nodup={}'\
        .format(access_token,path,ondup)
    localfile = "'"+localfile+"'"
    add = "--form file=@"+localfile
    cmds = "curl -X POST -k -L {} \"{}\"".format(add,url)
    cmdans = cmd(cmds)
    apierr(cmdans)
    return cmdans

def delete_file(access_token,path):
    path = getpath(path)
    dele = do_api('https://pcs.baidu.com/rest/2.0/pcs/file',
                  "method=delete&access_token={}&path={}".format(access_token, path), 'GET')
    dele = dele.split('\n')[:-1]
    apierr(dele)
    return dele

def fetch_file(access_token,path,url):
    path = getpath(path)
    fetch = do_api("https://pcs.baidu.com/rest/2.0/pcs/services/cloud_dl",
                   "method=add_task&access_token={}&save_path={}&source_url={}"
                   .format(access_token,path,url),
                   "GET")
    fetch = fetch.split('\n')[:-1]
    apierr(fetch)
    return fetch



def du_init(quickinit = False):
    BPCSU_KEY = 'uFBSHEwWE6DD94SQx9z77vgG'
    BPCSU_SEC = '7w6wdSFsTk6Vv586r1W1ozHLoDGhXogD'
    BPCSU_FNAME = 'bpcs_uploader'
    if quickinit:
        appkey = BPCSU_KEY
        appsec = BPCSU_SEC
        appname = BPCSU_FNAME
    else:
        print("Please enter your PSC App API Key. You can get this key by visiting http://developer.baidu.com/dev#/create"
              "If you have already created an app, you can visit http://developer.baidu.com/console#/app and get it in your app's info."
              "If you don't want to bother creating an app, you can press Enter to use the demo API Key."
              "Doing so (without your own API Key/Secret) will cause the access-token to expire every 30 days, and you'll have to"
              "re-initialize when it expires.")
        appkey = raw_input("APP API KEY {} :".format(BPCSU_KEY))
        appkey = appkey if appkey != '' else BPCSU_KEY
        print("APP API key has been set to {} .".format(appkey))
        if appkey == BPCSU_KEY:
            print("Demo key detected. Using default API Sectet.")
            appsec = BPCSU_SEC
            appname = BPCSU_FNAME

        else:
            print("  Please enter your Baidu PSC App API Secret. If you have no idea what it is, keep it blank.")
            appsec = raw_input('APP API SECRET {} :'.format(BPCSU_SEC))

            prepathfile = os.path.join(CONFIG_DIR,'appname')
            print("Please enter your app's folder name. You can choose to input this later in the file {}."
                  "** Why do I have to enter the app's folder name? Please check the FAQs. **"
                  "If your app's name has Chinese characters, please ensure that your client supports UTF-8 encoding."
                  "Below are some Chinese characters for testing. Please make sure that you can read them before you enter Chinese here."
                  "这里是一些中文字符。"
                  "If you can't read the characters above, please press Enter and change it manually within the file {}.".format(prepathfile,prepathfile))
            appname = raw_input("APP`s Folder Name :")

    with open(os.path.join(CONFIG_DIR, 'appkey'), 'w')as f:
        f.write(appkey)
    with open(os.path.join(CONFIG_DIR, 'appsec'), 'w')as f:
        f.write(appsec)
    with open(os.path.join(CONFIG_DIR,'appname'),'w')as f:
        f.write(appname)

